INSERT INTO TB_USER(ID_USER, NM_USER, TX_EMAIL, TX_PASSWORD, TX_ROLE) VALUES (101, 'usuario', 'usuario@gmail.com', '$2a$10$BUkQoNYCmhUzereAucA.lObiDmDc2LyCdHEHhJuGN0HdE008HPyYO', 'ROLE_USER');

INSERT INTO TB_CRYPTOCURRENCY(ID_CRYPTOCURRENCY, NM_CRYPTOCURRENCY, TX_PATH_ICON, TX_SYMBOL) VALUES (101, 'Bitcoin', 'bitcoin.png', 'BTC');

INSERT INTO TB_ALERT(ID_ALERT, NR_TARGET_VALUE, ID_CRYPTOCURRENCY, ID_USER, TP_ALERT, IS_ACTIVE, NR_SENDING) VALUES (101, 51670, 101, 101, 'TO_UP', TRUE, 0);
INSERT INTO TB_ALERT(ID_ALERT, NR_TARGET_VALUE, ID_CRYPTOCURRENCY, ID_USER, TP_ALERT, IS_ACTIVE, NR_SENDING) VALUES (102, 305, 101, 101, 'TO_DOWN', TRUE, 0);