CREATE TABLE TB_USER(
    ID_USER SERIAL PRIMARY KEY,
    NM_USER VARCHAR(255) NOT NULL,
    TX_EMAIL VARCHAR(100) NOT NULL UNIQUE,
    TX_PASSWORD VARCHAR(255) NOT NULL,
    TX_ROLE VARCHAR(255) NOT NULL
);