ALTER TABLE IF EXISTS public.TB_ALERT
    ADD COLUMN TP_ALERT VARCHAR(100) NULL;


UPDATE TB_ALERT SET TP_ALERT = 'TO_UP' WHERE TP_ALERT IS NULL;


ALTER TABLE IF EXISTS public.TB_ALERT
    ALTER COLUMN TP_ALERT SET NOT NULL;