ALTER TABLE IF EXISTS public.TB_ALERT
    ADD CONSTRAINT FK_USER FOREIGN KEY(ID_USER) REFERENCES TB_USER(ID_USER);

ALTER TABLE IF EXISTS public.TB_ALERT
    ADD CONSTRAINT FK_CRYPTOCURRENCY FOREIGN KEY (ID_CRYPTOCURRENCY) REFERENCES TB_CRYPTOCURRENCY (ID_CRYPTOCURRENCY);